### ISSUE TITLE
Missing License declaration

### ISSUE THREAD

**Issue by gtbu** [magnusmartin85/off-canvas-menu#19]
Your menu works great now. Is there a way that You add a license(MIT - GPL - Apache ) please. In some countries _no license_ means that all rights are kept.

**Comment by magnusmartin85** [comment]
Hey gtbu,

thank you for reaching out. Happy to see someone use it :) I will spend some time investigating. I will come back to you soon.

Best regards

**Comment by magnusmartin85** [comment]
Hi @gtbu,

I added a [GPL-3.0 license](https://github.com/magnusmartin85/off-canvas-menu/blob/master/COPYING).
